### ISSUE TITLE
README verbessern

### ISSUE THREAD

**Issue by abrock** [habo/stickes#1]
Auf meinem System funktioniert der editor nicht, wenn ich "mvn exec:java" ausführe bekomme ich beim ersten Versuch:

https://github.com/abrock/Katzenfutter/blob/master/stickes/erster-versuch.txt

beim zweiten Versuch:

https://github.com/abrock/Katzenfutter/blob/master/stickes/zweiter-versuch.txt

beim dritten Versuch mit "mvn exec:java -X -e":

https://github.com/abrock/Katzenfutter/blob/master/stickes/dritter-versuch-alle-debug-ausgaben.txt

Ich habe dann mal "mvn install sonar:sonar" ausgeführt, das bricht auch mit einem Fehler ab:

https://github.com/abrock/Katzenfutter/blob/master/stickes/sonar-log.txt

Aber danach funktioniert der Editor. Das müsste man in der README vielleicht deutlicher machen.

**Comment by habo** [comment]
Die README wurde gerade aktualisiert, der Befehl sollte "mvn compile exec:java" heißen. Sorry.
